apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-external-secret
  namespace: default
spec:
  # Frecuencia de sincronización con GCP Secret Manager
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  # El K8s Secret que ESO va a crear/mantener automáticamente
  target:
    name: rabbitmq-secret
    creationPolicy: Owner

  # Mapeo: extrae cada campo del JSON del secreto de GCP
  data:
    - secretKey: username       # clave en el K8s Secret
      remoteRef:
        key: rabbitmq-credentials   # nombre del secreto en GCP Secret Manager
        property: username          # campo dentro del JSON {"username":...,"password":...}

    - secretKey: password
      remoteRef:
        key: rabbitmq-credentials
        property: password
