apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: project-f3583ede-db03-4872-95c
      auth:
        workloadIdentity:
          # Service Account de GCP que tiene rol secretmanager.secretAccessor
          serviceAccountRef:
            name: eso-ksa           # K8s ServiceAccount anotada con la SA de GCP
            namespace: external-secrets
