apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-gpu-deployment
  namespace: g-naj
  labels:
    app: worker-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-gpu
  template:
    metadata:
      labels:
        app: worker-gpu
    spec:

      # Toleration para nodos con GPU (k3s suele tener taint nvidia.com/gpu=present:NoSchedule)
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule

      containers:
      - name: worker-gpu
        image: us-central1-docker.pkg.dev/project-f3583ede-db03-4872-95c/stickerchain/sticker-hit7:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1   # Solicita 1 GPU física al device plugin de NVIDIA
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: url
