apiVersion: apps/v1
kind: Deployment
metadata:
  name: trp-deployment
  namespace: default
  labels:
    app: trp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trp
  template:
    metadata:
      labels:
        app: trp
    spec:
      nodeSelector:
        node_role: applications
      containers:
      - name: trp
        image: us-central1-docker.pkg.dev/project-f3583ede-db03-4872-95c/stickerchain/sticker-trp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: PORT
          value: "8001"
        - name: REDIS_HOST
          value: "redis-service"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
---
apiVersion: v1
kind: Service
metadata:
  name: trp-service
  namespace: default
spec:
  selector:
    app: trp
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
